---
title: "SWC - R"
date: "6 February 2018"
output: html_document
---

Simplfied version of http://swcarpentry.github.io/r-novice-gapminder/

## Introduction to R and Rstudio
  ( http://swcarpentry.github.io/r-novice-gapminder/01-rstudio-intro/ )

key points:

- Rstudio panels
- using R as calculator
- comparing things
- variables and assignment
  - valid names
- rm()
- install.packages()
    - ggplot2, dplyr, gapminder

## Projects
 ( http://swcarpentry.github.io/r-novice-gapminder/02-project-intro/ )

Create project and setup dirs:

- src
- data
- docs
- results

Download data from https://raw.githubusercontent.com/resbaz/r-novice-gapminder-files/master/data/gapminder-FiveYearData.csv into data

## Seeking help
  ( http://swcarpentry.github.io/r-novice-gapminder/03-seeking-help/ )

- help()
    - quick explain of results
- ?? for fuzzy searching
- google
- stack overflow

## Exploring dataframes
  ( http://swcarpentry.github.io/r-novice-gapminder/04-data-structures-part1/ )

- read.csv()
    - header = TRUE
    - stringsAsFactors = FALSE
    - sep = ',' or '\t'

Viewing

- class()
- str()
- dim()
    - nrow()
    - ncol()
- View()
- head()
- names()
    - colnames()


## ggplot2
  ( http://swcarpentry.github.io/r-novice-gapminder/08-plot-ggplot2/ )

Introduce idea of mapping data to aesthetics and representing the data with geoms

- library("ggplot2")
- ggplot()
- aes()
- geoms
    - geom_point()
    - geom_line()
- facets
    - facet_wrap()
  
## Dataframe manipulation
  ( http://swcarpentry.github.io/r-novice-gapminder/13-dplyr/ )

- library("dplyr")
- select()
- %>% 
- filter()
- group_by()
- summarise()
- mutate()

show dplyr being piped into ggplot

## Writing data
  ( http://swcarpentry.github.io/r-novice-gapminder/11-writing-data/ )

- ggave
- write.table
    - tsv
    - csv

## Functions
  ( http://swcarpentry.github.io/r-novice-gapminder/10-functions/ )

```
my_function <- function(){ 

}
```

- arguments
- return
- stopifnot
- combining functions

## control flow
  ( http://swcarpentry.github.io/r-novice-gapminder/07-control-flow/ )

- if
    - if else
- ifelse
- for
